---
- name: Create and Configure Azure Storage Account
  hosts: localhost
  gather_facts: no
  tasks:
   - name: Create container foo and upload a file
     azure_rm_storageblob:
       resource_group: "{{ resource_group_name }}"
       storage_account_name: "{{ storage_account_name }}"
       container: foo
       blob: graylog.png
       src: graylog.png
       public_access: container
       content_type: 'application/image'
