---
- name: Create and Configure Azure Storage Account
  hosts: localhost
  tasks:
    - name: Configure blob service properties
      azure_rm_storageaccount_blobservice:
        resource_group: "{{ resource_group_name }}"
        storage_account_name: "{{ storage_account_name }}"
        properties:
          delete_retention_policy:
            days: 7
          enable_versioning: true
        state: present

    - name: Configure encryption settings
      azure_rm_storageaccount_encryption:
        resource_group: "{{ resource_group_name }}"
        storage_account_name: "{{ storage_account_name }}"
        encryption:
          services:
            blob:
              enabled: true
            file:
              enabled: true
          key_source: "Microsoft.Storage"
        state: present
